@rem ________________________________________________________
@rem  Create file functions_full.dat
@rem         from functions_PHP.dat
@rem         and  functions_GTK.dat
@rem --------------------------------------------------------
@rem  Copyright 2009 Pierre Fauconnier  pf18387@users.sf.net
@rem --------------------------------------------------------
@rem  file functions_GTK.dat is generated by Gtk_Dumper2.php
@rem ________________________________________________________
copy functions_PHP.dat+functions_GTK.dat functions_full.dat
